import fs from 'node:fs';
const source = JSON.parse(fs.readFileSync(new URL('../specs/design-tokens.json', import.meta.url), 'utf8'));
const css = '/* Generated by npm run tokens:build — edit specs/design-tokens.json instead. */\n:root {\n' +
  Object.entries(source.tokens).map(([key, value]) => `  --${key}: ${value};`).join('\n') + '\n}\n';
const path = new URL('../app/tokens.css', import.meta.url);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(path) || fs.readFileSync(path, 'utf8') !== css) throw new Error('Tokens désynchronisés : exécuter npm run tokens:build');
  console.log('Design tokens synchronisés.');
} else fs.writeFileSync(path, css);
